### ISSUE TITLE
auth issues

### ISSUE THREAD

**Issue by raja** [deepgram/deepgram-brain-python#1]
`from deepgram import Brain
 
deepgram_client = Brain(user_id='XXX',token='XXXXX')

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/Users/raja/.venvs/backend/lib/python3.6/site-packages/deepgram/connection.py", line 30, in __init__
    self.login(**kwargs)
  File "/Users/raja/.venvs/backend/lib/python3.6/site-packages/deepgram/connection.py", line 64, in login
    self.signedUsername = self._checkReturn(requests.get("{}/users/login".format(self.url), auth=auth))[
  File "/Users/raja/.venvs/backend/lib/python3.6/site-packages/deepgram/connection.py", line 34, in _checkReturn
    value = response.json()
  File "/Users/raja/.venvs/backend/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by raja** [comment]
url should 'https://api.deepgram.com' instead of brain.deepgram.com 

s/api.d/brain.d/g

**Comment by greedyuser** [comment]
Thanks for posting this. I will adjust the docs page to reflect the state of the api url. Currently the URL is 'api.deepgram.com' but that will shortly be switched to 'brain.deepgram.com' which is why the default was set the way it is. Additionally, error handling and reporting will be improved to make this error clearer in the future. For now use the api url but expect it to change. 

I apologize for the time you spent debugging this!

I am leaving this issue open until the new api is running.

**Comment by greedyuser** [comment]
https://brain.deepgram.com is now live so the default url now works.

**Comment by raja** [comment]
Does api.deepgram redirect?

**Comment by greedyuser** [comment]
api.deepgram.com should be gone now with a page notifying the change. brain.deepgram.com points to all the same data. Sorry for the confusion on this!
